import {BigQuery} from "@google-cloud/bigquery";
import serviceAccount from "./meteorwallet-query-near.json";

const bigquery = new BigQuery({
    credentials: serviceAccount,
    projectId: "meteorwallet",
});

interface ExecuteSqlResult {
    status: 'success' | 'error';
    result?: Record<string, any>[];
    error?: string;
}

/**
 * This function will execute the SQL query and return the result.
 *
 * The SQL query will be in the GoogleSQL dialect.
 *
 * The SQL query is generated by AI, we cannot guarantee that it will be valid. Neither we can guarantee that it will not perform a full table scan.
 *
 * Maybe we can add some checks to see how much data the query will scan and if it is too much, return an error.
 *
 * @param sql
 * @returns
 */
export async function executeSql(sql: string): Promise<ExecuteSqlResult> {
    try {
        // do whatever necessary
        const result = await bigquery.query({
            query: sql,
        });

        return {
            status: 'success',
            result,
        };
    } catch (err: any) {
        return {
            status: 'error',
            error: err.toString(),
        };
    }
}
